In [15]:
import numpy as np
import time
import torch

from torch.autograd import Variable

## Tensor

### 0차원 텐서 : 스칼라

In [11]:
x = torch.tensor(37)

print(x)

tensor(37)


In [12]:
print(x.dim())

0


### 1차원 텐서 : 벡터

In [10]:
lotto = torch.FloatTensor([5,18,30,41,43.0,45.0])

lotto.size()

torch.Size([6])

### 2차원 텐서 : 행렬

### 3 차원 텐서

코드를 실행하기 전에 이미지를 다운받아서 사용하자

https://user-images.githubusercontent.com/26184454/53178675-a7545800-3635-11e9-9244-0461707cc0ef.jpg



In [ ]:
#이미지를 64 X 64 사이즈로 불러오기
img = Image.open('pepe.jpg').resize((128,128))

#이미지를 넘파이 배열로 바꾸기
pepe = np.array(img)

#바꾼 넘파이 배열을 텐서로 바꾸기
pepe_tensor = torch.from_numpy(pepe)
pepe_tensor.size()

In [ ]:
plt.imshow(pepe_tensor)

### 텐서 슬라이싱

In [ ]:
plt.imshow(pepe_tensor[:,:,2].numpy())

In [ ]:
plt.imshow(pepe_tensor[20:110,20:110,:].numpy())

### 4차원 텐서

### 5차원 텐서

### GPU 텐서

In [16]:
a = torch.rand(10000,10000)
b = torch.rand(10000,10000)

#cpu 계산
start_time = time.time() 
a.matmul(b)

cpu_times = time.time() - start_time
print("CPU로 돌릴때 걸린 시간:", cpu_times)
 
#GPU 연산
a = a.cuda()
b = b.cuda()

start_time = time.time()
a.matmul(b)
gpu_times = time.time() - start_time
print("GPU로 돌릴때 걸린 시간:", gpu_times)


CPU로 돌릴때 걸린 시간: 12.686848640441895
GPU로 돌릴때 걸린 시간: 1.1522679328918457


## Variable

In [17]:
ones = torch.ones(2,2)
print(ones)

tensor([[1., 1.],
        [1., 1.]])


In [18]:
x = Variable(ones, requires_grad = True)
y = x.mean()

y.backward()

In [19]:
x.grad

tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])

In [20]:
x.grad_fn

In [21]:
x.data

tensor([[1., 1.],
        [1., 1.]])

In [22]:
y.grad_fn

## 신경망

### 신경망에 사용할 데이터 생성하기

In [24]:
def get_data():
    train_X = np.asarray([3.3,4.4,5.5,6.71,6.93,4.168,9.779,6.182,7.59,2.167,
                         7.042,10.791,5.313,7.997,5.654,9.27,3.1])
    train_Y = np.asarray([1.7,2.76,2.09,3.19,1.694,1.573,3.366,2.596,2.53,1.221,
                         2.827,3.465,1.65,2.904,2.42,2.94,1.3])
    dtype = torch.FloatTensor
    X = Variable(torch.from_numpy(train_X).type(dtype),requires_grad=False).view(17,1)
    y = Variable(torch.from_numpy(train_Y).type(dtype),requires_grad=False)
    
    return X,y

### 학습 파라미터 생성

In [25]:
def get_weights():
    w = Variable(torch.randn(1),requires_grad = True)
    b = Variable(torch.randn(1),requires_grad = True)
    
    return w,b

### 신경망 모델 : 네트워크 구현

선형 관계 y = wx + b

In [26]:
def simple_network(x):
    y_pred = torch.matmul(x,w) + b
    
    return y_pred

### 오차 함수
Sum of Squared Error (SSE) 사용

In [27]:
def loss_fn(y, y_pred):
    loss = (y_pred - y).pow(2).sum()
    for param in [w,b]:
        if not param.grad is None : param.grad.data.zero_()
    loss.backward()
    
    return loss.data[0]

### 최적화

In [28]:
def optimize(learning_rate):
    w.data -= learning_rate * w.grad.data
    b.data -= learning_rate * b.grad.data